spring:
  # 表示放在classpath的i18n文件夹，文件前缀为mess
  messages:
    basename: language/messages
  datasource:
    # driverClassName: net.sf.log4jdbc.DriverSpy
    #url: jdbc:log4jdbc:mysql://mysql.zhangzp.cn:3306/hadoop2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.75.95.136:3306/test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    username: test
    password: LxY7wQfJs_jsX
    filters: stat
    maxActive: 30
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    maxIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 1200000

# 自定义属性
cupSize: B

man:
  telephone: 13308629879
  realName: zhangzaipeng

#mybatis:
  #typeAliasesPackage: com.hwz.**.domain
  # mapperLocations: classpath:/com/exchange/**/mapper/*.ibatis.xml
  # configLocation: classpath:/mybatis-config.xml
