spring:
  # 表示放在classpath的i18n文件夹，文件前缀为mess
  messages:
    basename: language/messages
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # driverClassName: net.sf.log4jdbc.DriverSpy
    url: jdbc:mysql://39.108.113.220:3306/mexc?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    #url: jdbc:log4jdbc:mysql://mysql.zhangzp.cn:3306/hadoop2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: lailekeji1q2w3e!@#

# 自定义属性
cupSize: B

man:
  telephone: 13308629879
  realName: zhangzaipeng