spring:
  # 表示放在classpath的i18n文件夹，文件前缀为mess
  messages:
    basename: language/messages

# 自定义属性
cupSize: B

man:
  telephone: 13308629879
  realName: zhangzaipeng

mybatis:
  #typeAliasesPackage: com.hwz.**.domain
  mapperLocations: classpath:/com/shex/**/mapper/*.ibatis.xml
  # configLocation: classpath:/mybatis-config.xml