spring:
  datasource:
    # driverClassName: net.sf.log4jdbc.DriverSpy
    #url: jdbc:log4jdbc:mysql://mysql.zhangzp.cn:3306/hadoop2?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.75.95.136:3306/test?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8&amp;zeroDateTimeBehavior=convertToNull
    username: test
    password: LxY7wQfJs_jsX

mybatis:
  #typeAliasesPackage: com.hwz.**.domain
  mapperLocations: classpath:/com/shex/**/mapper/*.ibatis.xml
  # configLocation: classpath:/mybatis-config.xml